# MP Configuration File
# This file is used by mp.sh and the Grading System to determine environment settings.
# It will be overwritten by the TA during the Official Grading phase.

# Assignment Identifier
ASSIGNMENT="mp0"

# Grading Deadline (ISO 8601)
DEADLINE="2026-03-31T23:59:59Z"



# TA Email Whitelist (Space separated)
# Any commit by these emails will be SKIPPED by the local test runner
# and EXCLUDED from the official grading target.
TA_EMAILS="ta_lead@ntu.edu.tw ta2@ntu.edu.tw"
