# MP Configuration File
# This file is used by mp.sh and the Grading System to determine environment settings.
# It will be overwritten by the TA during the Official Grading phase.

# Assignment Identifier
ASSIGNMENT="mp1"

# Grading Deadline (ISO 8601)
DEADLINE="2026-03-23T23:59:59+08:00"



# TA Email Whitelist (Space separated)
# Any commit by these emails will be SKIPPED by the local test runner
# and EXCLUDED from the official grading target.
TA_EMAILS="dylan910413@gmail.com jovyttayauwanta@gmail.com"
